name: "ensemble"
platform: "ensemble"
max_batch_size: 256

# Input: Same as preprocessing
inputs [
  {
    name: "QUERY"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "LORA_ADAPTER_NAME"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
  }
]
# Output: Same as postprocessing
outputs [
  {
    name: "RESPONSE"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

# Ensemble chaining:
# QUERY -> preprocessing -> INPUT_ID -> tensorrt_llm
# LORA_ADAPTER_NAME -> preprocessing -> LORA_NAMES -> tensorrt_llm
# tensorrt_llm -> OUTPUT_ID -> postprocessing -> RESPONSE
ensemble_scheduling {
  step [
    {
      model_name: "preprocessing"
      model_version: -1
      input_map [
        {
          key: "QUERY"
          value: "QUERY"
        },
        {
          key: "LORA_ADAPTER_NAME"
          value: "LORA_ADAPTER_NAME"
        }
      ]
      output_map [
        {
          key: "INPUT_ID"
          value: "ensemble_input_id"
        },
        {
          key: "REQUEST_INPUT_LEN"
          value: "ensemble_request_input_len"
        },
        {
          key: "LORA_NAMES"
          value: "ensemble_lora_names"
        }
      ]
    },
    {
      model_name: "tensorrt_llm"
      model_version: -1
      input_map [
        {
          key: "input_ids"
          value: "ensemble_input_id"
        },
        {
          key: "input_lengths"
          value: "ensemble_request_input_len"
        },
        {
          key: "lora_names"
          value: "ensemble_lora_names"
        }
      ]
      output_map [
        {
          key: "output_ids"
          value: "ensemble_output_id"
        }
      ]
    },
    {
      model_name: "postprocessing"
      model_version: -1
      input_map [
        {
          key: "OUTPUT_ID"
          value: "ensemble_output_id"
        }
      ]
      output_map [
        {
          key: "RESPONSE"
          value: "RESPONSE"
        }
      ]
    }
  ]
}
